name: Playwright Crossbrowsers Tests

'on':
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Custom_Linux_Grid:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Install dependencies using Yarn
      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn install
          yarn add playwright
          yarn add typescript ts-node @types/node

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      # Step 5: Compile TypeScript
      - name: Compile TypeScript
        run: yarn tsc


      # Step 6: Ensure Playwright Artifacts exists
      - name: Ensure Playwright Artifacts Directory Exists
        run: |
             mkdir -p reports/playwright-report

      # Step 7: Run Playwright Tests across all browsers in parallel
      - name: Run Playwright Tests across all browsers
        run: |
          echo "Running tests on all browsers: Chromium, Firefox, and WebKit (Edge)"
          
          # Run tests across all browsers in parallel using the `projects` configuration
          # The `&` operator runs these commands in parallel, and `wait` ensures that they all finish before continuing
          xvfb-run -a yarn playwright test --project=chromium --reporter=html --output=reports/playwright-report/chromium &   # Chromium
          xvfb-run -a yarn playwright test --project=firefox --reporter=html --output=reports/playwright-report/firefox &   # Firefox
          xvfb-run -a yarn playwright test --project=webkit --reporter=html --output=reports/playwright-report/webkit &   # WebKit (Edge)
          wait  # Wait for all browsers to finish running

      # Step 8: Confirm Playwright artifacts generation
      - name: List Playwright artifacts
        run: |
          echo "Listing the contents of reports/playwright-report:"
          ls -R reports/playwright-report

      # Step 9: Wait for the test results to generate (optional)
      - name: Wait for the test results to generate
        run: |
          sleep 20  # Adjust time as needed to ensure reports are written
      
      # Step 10: Upload Playwright Report HTML as Pipeline Artifact
      - name: Upload Playwright Report HTML as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Playwright_Report_HTML
          path: reports/playwright-report/**/index.html